'use client';
import { useEffect, useMemo, useState } from 'react';

type Artist={id?:string;name:string;slug?:string};
type Video={id:string;title:string;thumbnail_url:string|null;status:string;is_interview:boolean;transcript_status:string;moment_count:number;artists:Artist[]};
type Moment={id:string;video_id:string;video_title:string;youtube_video_id:string;thumbnail_url:string|null;start_seconds:number;title:string;summary:string|null;topic_label:string|null;artist_name:string;artist_slug:string|null};
type YouTubeConnection={connected:boolean;channel_title?:string|null};
type Tab='videos'|'transcribed'|'ai'|'check'|'final';
type ArtistEdit={videoId:string;name:string;error:string;saving:boolean};

function clock(seconds:number){const m=Math.floor(seconds/60);const s=seconds%60;return `${m}:${String(s).padStart(2,'0')}`}
function groupByArtist(items:Moment[]){const map=new Map<string,Moment[]>();for(const m of items){const key=m.artist_name||'Unmatched artist';map.set(key,[...(map.get(key)||[]),m])}return [...map.entries()].sort((a,b)=>a[0].localeCompare(b[0]))}
function groupByVideo(items:Moment[]){const map=new Map<string,Moment[]>();for(const m of items)map.set(m.video_id,[...(map.get(m.video_id)||[]),m]);return [...map.values()]}

export function VideoArchiveDesk(){
 const [videos,setVideos]=useState<Video[]>([]);const [moments,setMoments]=useState<Moment[]>([]);const [checkMoments,setCheckMoments]=useState<Moment[]>([]);const [publishedMoments,setPublishedMoments]=useState<Moment[]>([]);const [yt,setYt]=useState<YouTubeConnection>({connected:false});const [tab,setTab]=useState<Tab>('videos');const [busy,setBusy]=useState('');const [msg,setMsg]=useState('');const [transcript,setTranscript]=useState<Record<string,string>>({});const [selected,setSelected]=useState<Set<string>>(new Set());const [artistEdit,setArtistEdit]=useState<ArtistEdit|null>(null);const [confirmKey,setConfirmKey]=useState('');
 async function load(){const r=await fetch('/api/admin/video-archive');if(!r.ok)return;const j=await r.json();setVideos(j.videos||[]);setMoments(j.moments||[]);setCheckMoments(j.checkMoments||[]);setPublishedMoments(j.publishedMoments||[]);setYt(j.youtubeConnection||{connected:false});setSelected(prev=>new Set([...prev].filter(id=>(j.videos||[]).some((v:Video)=>v.id===id))))}
 useEffect(()=>{load();const p=new URLSearchParams(window.location.search);if(p.get('youtube')==='connected')setMsg(`YouTube connected${p.get('channel')?`: ${p.get('channel')}`:''}.`);else if(p.get('youtube')==='error')setMsg(p.get('message')||'YouTube connection failed.');},[]);
 async function act(body:Record<string,unknown>,key=''){setBusy(key);setMsg('');const r=await fetch('/api/admin/video-archive',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify(body)});const j=await r.json();setBusy('');setMsg(r.ok?(j.artist?`Artist changed to ${j.artist.name}.`:j.created?`Created ${j.created} AI moments.`:j.updated!=null?`${j.updated} items moved.`:j.deleted!=null?`${j.deleted} videos deleted.`:j.found===true?'Transcript pulled from YouTube.':j.found===false?(j.reason||'No transcript found.'):'Saved.'):j.error||'Action failed');if(r.ok)await load();return {ok:r.ok,data:j}}
 async function sync(){setBusy('sync');setMsg('Starting YouTube sync…');let reset=true,total=0;try{while(true){const r=await fetch('/api/admin/video-archive',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({action:'sync',channelKey:'oshioma',reset})});const j=await r.json();if(!r.ok)throw new Error(j.error||'Sync failed');reset=false;total+=Number(j.processed||0);setMsg(`YouTube sync: ${total} videos processed${j.done?' — complete.':'…'}`);if(j.done)break}await load()}catch(e){setMsg(e instanceof Error?e.message:'Sync failed')}finally{setBusy('')}}
 async function toggleInterview(v:Video){const turningOn=!v.is_interview;setBusy(v.id);try{const r=await fetch('/api/admin/video-archive',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({action:'update',videoId:v.id,isInterview:turningOn})});const j=await r.json();if(!r.ok)throw new Error(j.error||'Could not update video');setMsg(turningOn&&j.autoTranscript?.found?'Interview marked ✓ Transcript ready — moved to Transcribed.':turningOn?(j.autoTranscript?.error||j.autoTranscript?.reason||'Interview marked.'):'Interview flag removed.');await load()}catch(e){setMsg(e instanceof Error?e.message:'Could not update video')}finally{setBusy('')}}
 async function pullAllInterviewTranscripts(){setBusy('bulk-transcripts');let processed=0,ready=0,failed=0;try{while(true){const r=await fetch('/api/admin/video-archive',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({action:'pull-interview-transcripts',limit:8})});const j=await r.json();if(!r.ok)throw new Error(j.error||'Transcript backfill failed');processed+=Number(j.processed||0);ready+=Number(j.ready||0);failed+=Number(j.failed||0);setMsg(`Transcripts: ${processed} checked · ${ready} ready · ${failed} unavailable${j.remaining?` · ${j.remaining} remaining…`:' — complete.'}`);if(!j.remaining||!j.processed)break}await load()}catch(e){setMsg(e instanceof Error?e.message:'Transcript backfill failed')}finally{setBusy('')}}
 const workVideos=useMemo(()=>videos.filter(v=>!v.is_interview||v.transcript_status!=='ready'),[videos]);const transcribedVideos=useMemo(()=>videos.filter(v=>v.is_interview&&v.transcript_status==='ready'&&v.moment_count===0),[videos]);const visibleVideos=tab==='videos'?workVideos:tab==='transcribed'?transcribedVideos:[];const interviewsNeedingTranscript=videos.filter(v=>v.is_interview&&['missing','partial'].includes(v.transcript_status)).length;const tabs:[Tab,string,number][]=[['videos','1 · Videos',workVideos.length],['transcribed','2 · Transcribed',transcribedVideos.length],['ai','3 · AI moments',moments.length],['check','4 · Check',checkMoments.length],['final','5 · Final clips',publishedMoments.length]];const allSelected=visibleVideos.length>0&&visibleVideos.every(v=>selected.has(v.id));
 function toggle(id:string){setSelected(prev=>{const n=new Set(prev);n.has(id)?n.delete(id):n.add(id);return n})}function toggleAll(){setSelected(allSelected?new Set():new Set(visibleVideos.map(v=>v.id)))}
 async function deleteSelected(){if(!selected.size)return;const key='delete-selected';if(confirmKey!==key){setConfirmKey(key);return}const r=await act({action:'delete-videos',videoIds:[...selected]},key);setConfirmKey('');if(r.ok)setSelected(new Set())}
 async function sendAllToCheck(){if(!moments.length)return;const key='send-all-check';if(confirmKey!==key){setConfirmKey(key);return}await act({action:'bulk-stage'},'bulk-stage');setConfirmKey('');setTab('check')}
 async function bulkCheck(decision:'publish'|'reject'){const key=`bulk-${decision}`;if(confirmKey!==key){setConfirmKey(key);return}await act({action:'bulk-review',decision},key);setConfirmKey('');if(decision==='publish')setTab('final')}
 async function hideMoment(m:Moment){const key=`hide-${m.id}`;if(confirmKey!==key){setConfirmKey(key);return}await act({action:'hide-moment',momentId:m.id},m.id);setConfirmKey('')}
 function beginArtistEdit(videoId:string,current:string){setArtistEdit({videoId,name:current==='Unmatched artist'?'':current,error:'',saving:false})}
 async function saveArtist(videoId:string){if(!artistEdit?.name.trim())return;setArtistEdit({...artistEdit,saving:true,error:''});const r=await fetch('/api/admin/video-archive',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({action:'change-artist',videoIds:[videoId],artistName:artistEdit.name.trim()})});const j=await r.json();if(!r.ok){setArtistEdit({...artistEdit,saving:false,error:j.error||'Could not change artist'});return}await load();setArtistEdit(null);setMsg(`Artist changed to ${j.artist.name}.`)}

 const momentCard=(m:Moment,stage:'ai'|'check'|'final')=><div className="adminCard" key={m.id} style={{padding:14}}><div style={{display:'grid',gridTemplateColumns:m.thumbnail_url?'160px minmax(0,1fr) auto':'minmax(0,1fr) auto',gap:16,alignItems:'start'}}>{m.thumbnail_url&&<a href={`https://www.youtube.com/watch?v=${m.youtube_video_id}&t=${m.start_seconds}s`} target="_blank" rel="noreferrer" style={{display:'block',position:'relative'}}><img src={m.thumbnail_url} alt="" style={{width:160,aspectRatio:'16/9',objectFit:'cover',borderRadius:9,display:'block'}}/><span style={{position:'absolute',right:7,bottom:7,background:'rgba(0,0,0,.75)',color:'#fff',padding:'3px 6px',borderRadius:5,fontSize:12,fontWeight:800}}>{clock(m.start_seconds)}</span></a>}<div><div style={{fontSize:17,fontWeight:750}}>{m.title}</div><div className="adminSub" style={{marginTop:3}}>{m.video_title}{m.topic_label?` · ${m.topic_label}`:''}</div>{m.summary&&<p style={{margin:'10px 0 0',lineHeight:1.5}}>{m.summary}</p>}</div><div style={{display:'flex',gap:7,flexWrap:'wrap',justifyContent:'flex-end'}}><a className="btn btnSmall" target="_blank" rel="noreferrer" href={`https://www.youtube.com/watch?v=${m.youtube_video_id}&t=${m.start_seconds}s`}>{stage==='check'?'Check on YouTube ↗':'Open moment ↗'}</a>{stage==='ai'&&<><button className="btn btnSmall" disabled={!!busy} onClick={()=>act({action:'stage-moment',momentId:m.id},m.id)}>Send to check →</button><button className="btn btnSmall" disabled={!!busy} onClick={()=>hideMoment(m)}>{confirmKey===`hide-${m.id}`?'Confirm reject':'Reject'}</button></>}{stage==='check'&&<><button className="btn btnSmall" disabled={!!busy} onClick={()=>act({action:'review',momentId:m.id,decision:'publish'},m.id)}>Publish ✓</button><button className="btn btnSmall" disabled={!!busy} onClick={()=>act({action:'review',momentId:m.id,decision:'reject'},m.id)}>Reject</button></>}{stage==='final'&&<button className="btn btnSmall" disabled={!!busy} onClick={()=>hideMoment(m)}>{confirmKey===`hide-${m.id}`?'Confirm hide':'Hide'}</button>}</div></div></div>;
 const artistGroups=(items:Moment[],stage:'ai'|'check'|'final')=>groupByArtist(items).map(([artist,artistMoments])=><section key={artist} style={{marginTop:28}}><div style={{borderBottom:'1px solid var(--border)',paddingBottom:8}}><div style={{fontSize:23,fontWeight:800}}>{artist}</div><div className="adminSub">{artistMoments.length} {stage==='final'?'published clip':'moment'}{artistMoments.length===1?'':'s'}</div></div>{groupByVideo(artistMoments).map(videoMoments=>{const first=videoMoments[0];const editing=artistEdit?.videoId===first.video_id;return <div key={first.video_id} style={{marginTop:16,padding:'14px 0 4px',borderBottom:'1px solid var(--border)'}}><div style={{display:'flex',justifyContent:'space-between',alignItems:'start',gap:12,flexWrap:'wrap',marginBottom:10}}><div><div style={{fontWeight:800,fontSize:16}}>{first.video_title}</div><div className="adminSub">{videoMoments.length} clip{videoMoments.length===1?'':'s'} from this interview</div></div><div style={{display:'flex',gap:8,flexWrap:'wrap'}}><button className="btn btnSmall" disabled={!!busy} onClick={()=>editing?setArtistEdit(null):beginArtistEdit(first.video_id,artist)}>{editing?'Close':'Change artist for this interview'}</button>{first.artist_slug&&<a className="btn btnSmall" href={`/artists/${first.artist_slug}`} target="_blank">Artist page ↗</a>}</div></div>{editing&&<div className="adminCard" style={{padding:12,marginBottom:12,maxWidth:600}}><div className="adminSub" style={{marginBottom:6}}>Correct only this interview: <b>{first.video_title}</b></div><div style={{display:'flex',gap:8,flexWrap:'wrap'}}><input value={artistEdit.name} onChange={e=>setArtistEdit({...artistEdit,name:e.target.value,error:''})} placeholder="Artist name" autoFocus style={{flex:'1 1 240px',padding:'8px 10px',minWidth:0}}/><button className="btn btnSmall" disabled={artistEdit.saving||!artistEdit.name.trim()} onClick={()=>saveArtist(first.video_id)}>{artistEdit.saving?'Saving…':'Save'}</button><button className="btn btnSmall" disabled={artistEdit.saving} onClick={()=>setArtistEdit(null)}>Cancel</button></div>{artistEdit.error&&<div style={{marginTop:8,color:'var(--danger,#b42318)',fontSize:13}}>{artistEdit.error}</div>}</div>}<div style={{display:'grid',gap:9}}>{videoMoments.map(m=>momentCard(m,stage))}</div></div>})}</section>);

 return <div><div className="adminHeader"><div><h1>Video Archive</h1><p className="adminSub">Find interview → transcript → AI moments → check → publish.</p></div><div style={{display:'flex',gap:8,flexWrap:'wrap'}}><a className="btn" href="/api/admin/video-archive/youtube/connect">{yt.connected?`YouTube ✓${yt.channel_title?` · ${yt.channel_title}`:''}`:'Connect YouTube'}</a><button className="btn" disabled={!!busy} onClick={sync}>{busy==='sync'?'Syncing…':'Sync YouTube'}</button>{yt.connected&&<button className="btn" disabled={!!busy||!interviewsNeedingTranscript} onClick={pullAllInterviewTranscripts}>{busy==='bulk-transcripts'?'Pulling…':`Pull transcripts${interviewsNeedingTranscript?` (${interviewsNeedingTranscript})`:''}`}</button>}</div></div>{msg&&<div className="adminCard" style={{marginTop:14,padding:'12px 16px'}}>{msg}</div>}<div style={{display:'flex',gap:8,marginTop:24,flexWrap:'wrap',paddingBottom:12,borderBottom:'1px solid var(--border)'}}>{tabs.map(([key,label,count])=><button key={key} className="btn" onClick={()=>{setTab(key);setSelected(new Set());setArtistEdit(null);setConfirmKey('')}} aria-pressed={tab===key} style={tab===key?{fontWeight:800}:undefined}>{label} <span style={{opacity:.65}}>({count})</span></button>)}</div>
 {(tab==='videos'||tab==='transcribed')&&<>{visibleVideos.length>0&&<div className="adminCard" style={{display:'flex',alignItems:'center',justifyContent:'space-between',gap:12,marginTop:14,flexWrap:'wrap'}}><label style={{display:'flex',alignItems:'center',gap:8}}><input type="checkbox" checked={allSelected} onChange={toggleAll}/><b>Select all visible</b><span className="adminSub">{selected.size?`${selected.size} selected`:`${visibleVideos.length} videos`}</span></label><button className="btn btnSmall" disabled={!selected.size||!!busy} onClick={deleteSelected}>{confirmKey==='delete-selected'?`Confirm delete ${selected.size}`:`Delete selected${selected.size?` (${selected.size})`:''}`}</button></div>}<div style={{display:'grid',gap:12,marginTop:12}}>{visibleVideos.map(v=><div className="adminCard" key={v.id}><div style={{display:'grid',gridTemplateColumns:'28px 120px minmax(240px,1fr) auto',gap:14,alignItems:'center'}}><input type="checkbox" checked={selected.has(v.id)} onChange={()=>toggle(v.id)}/>{v.thumbnail_url?<img src={v.thumbnail_url} alt="" style={{width:120,aspectRatio:'16/9',objectFit:'cover',borderRadius:8}}/>:<div/>}<div><b>{v.title}</b><div className="adminSub">{v.artists?.map(a=>a.name).join(', ')||'Artist not matched'} · transcript {v.transcript_status}</div></div><div style={{display:'flex',gap:7,flexWrap:'wrap'}}>{tab==='videos'&&<button className="btn btnSmall" disabled={busy===v.id} onClick={()=>toggleInterview(v)}>{v.is_interview?'Interview ✓':'Mark interview'}</button>}{tab==='videos'&&v.is_interview&&v.transcript_status!=='ready'&&yt.connected&&<button className="btn btnSmall" disabled={!!busy} onClick={()=>act({action:'pull-transcript',videoId:v.id},`transcript-${v.id}`)}>Retry transcript</button>}{tab==='transcribed'&&<button className="btn btnSmall" disabled={!!busy} onClick={async()=>{const r=await act({action:'extract',videoId:v.id},`moments-${v.id}`);if(r.ok)setTab('ai')}}>{busy===`moments-${v.id}`?'Creating moments…':'Generate AI moments →'}</button>}</div></div>{tab==='videos'&&v.is_interview&&v.transcript_status!=='ready'&&<div style={{marginTop:12}}><textarea value={transcript[v.id]||''} onChange={e=>setTranscript({...transcript,[v.id]:e.target.value})} placeholder="Paste transcript manually if YouTube captions are unavailable" rows={4} style={{width:'100%'}}/><button className="btn btnSmall" disabled={!transcript[v.id]?.trim()} onClick={()=>act({action:'update',videoId:v.id,transcript:transcript[v.id]})}>Save transcript</button></div>}</div>)}</div>{!visibleVideos.length&&<p className="adminSub" style={{marginTop:24}}>Nothing waiting at this stage.</p>}</>}
 {tab==='ai'&&<>{moments.length?<><div style={{display:'flex',justifyContent:'space-between',alignItems:'center',gap:12,marginTop:24,flexWrap:'wrap'}}><div><h2 style={{margin:0}}>AI moments</h2><p className="adminSub">First pass. Send the useful ones to Check.</p></div><button className="btn" disabled={!!busy} onClick={sendAllToCheck}>{confirmKey==='send-all-check'?`Confirm move ${moments.length} →`:'Send all to Check →'}</button></div>{artistGroups(moments,'ai')}</>:<p className="adminSub" style={{marginTop:24}}>No AI moments waiting.</p>}</>}
 {tab==='check'&&<>{checkMoments.length?<><div style={{display:'flex',justifyContent:'space-between',alignItems:'center',gap:12,marginTop:24,flexWrap:'wrap'}}><div><h2 style={{margin:0}}>Check before publishing</h2><p className="adminSub">Artist corrections are made one interview at a time.</p></div><div style={{display:'flex',gap:8}}><button className="btn" disabled={!!busy} onClick={()=>bulkCheck('publish')}>{confirmKey==='bulk-publish'?`Confirm publish ${checkMoments.length}`:'Publish all checked'}</button><button className="btn" disabled={!!busy} onClick={()=>bulkCheck('reject')}>{confirmKey==='bulk-reject'?`Confirm reject ${checkMoments.length}`:'Reject all'}</button></div></div>{artistGroups(checkMoments,'check')}</>:<p className="adminSub" style={{marginTop:24}}>Nothing waiting to be checked.</p>}</>}
 {tab==='final'&&<>{publishedMoments.length?<><div style={{marginTop:24}}><h2 style={{margin:0}}>Final clips</h2><p className="adminSub">Published clips grouped by artist, then by interview.</p></div>{artistGroups(publishedMoments,'final')}</>:<p className="adminSub" style={{marginTop:24}}>No final clips published yet.</p>}</>}</div>
}