'use client';
import { useEffect, useMemo, useState } from 'react';

type Artist={id?:string;name:string;slug?:string};
type Video={id:string;title:string;thumbnail_url:string|null;published_at:string|null;status:string;is_interview:boolean;transcript_status:string;moment_count:number;review_count:number;check_count:number;published_count:number;artists:Artist[]};
type Moment={id:string;video_id:string;video_title:string;youtube_video_id:string;start_seconds:number;title:string;summary:string|null;topic_label:string|null;artist_id:string|null;artist_name:string;artist_slug:string|null};
type YouTubeConnection={connected:boolean;channel_id?:string|null;channel_title?:string|null;connected_at?:string};
type Tab='videos'|'transcribed'|'ai'|'check'|'final';

function clock(seconds:number){const m=Math.floor(seconds/60);const s=seconds%60;return `${m}:${String(s).padStart(2,'0')}`}
function groupByArtist(items:Moment[]){const map=new Map<string,Moment[]>();for(const m of items){const key=m.artist_name||'Unmatched artist';map.set(key,[...(map.get(key)||[]),m])}return [...map.entries()].sort((a,b)=>a[0].localeCompare(b[0]))}

export function VideoArchiveDesk(){
 const [videos,setVideos]=useState<Video[]>([]);const [moments,setMoments]=useState<Moment[]>([]);const [checkMoments,setCheckMoments]=useState<Moment[]>([]);const [publishedMoments,setPublishedMoments]=useState<Moment[]>([]);const [busy,setBusy]=useState('');const [msg,setMsg]=useState('');const [transcript,setTranscript]=useState<Record<string,string>>({});const [selected,setSelected]=useState<Set<string>>(new Set());const [yt,setYt]=useState<YouTubeConnection>({connected:false});const [tab,setTab]=useState<Tab>('videos');
 async function load(){const r=await fetch('/api/admin/video-archive');if(r.ok){const j=await r.json();setVideos(j.videos||[]);setMoments(j.moments||[]);setCheckMoments(j.checkMoments||[]);setPublishedMoments(j.publishedMoments||[]);setYt(j.youtubeConnection||{connected:false});setSelected(prev=>new Set([...prev].filter(id=>(j.videos||[]).some((v:Video)=>v.id===id))))}}
 useEffect(()=>{load();const p=new URLSearchParams(window.location.search);if(p.get('youtube')==='connected')setMsg(`YouTube connected${p.get('channel')?`: ${p.get('channel')}`:''}.`);else if(p.get('youtube')==='error')setMsg(p.get('message')||'YouTube connection failed.');},[]);
 async function act(body:Record<string,unknown>,key=''){setBusy(key);setMsg('');const r=await fetch('/api/admin/video-archive',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify(body)});const j=await r.json();setMsg(r.ok?(j.artist?`Artist changed to ${j.artist.name}.`:j.created?`Created ${j.created} AI moments.`:j.updated!=null?`${j.updated} items moved.`:j.deleted!=null?`${j.deleted} videos deleted.`:j.found===true?'Transcript pulled from YouTube.':j.found===false?(j.reason||'No transcript found.'):'Saved.'):j.error||'Action failed');setBusy('');if(r.ok)await load();return {ok:r.ok,data:j}}
 async function sync(){setBusy('sync');setMsg('Starting YouTube sync…');let reset=true,total=0;try{while(true){const r=await fetch('/api/admin/video-archive',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({action:'sync',channelKey:'oshioma',reset})});const j=await r.json();if(!r.ok)throw new Error(j.error||'Sync failed');reset=false;total+=Number(j.processed||0);setMsg(`YouTube sync: ${total} videos processed${j.done?' — complete.':'…'}`);if(j.done)break}await load()}catch(e){setMsg(e instanceof Error?e.message:'Sync failed')}finally{setBusy('')}}
 async function toggleInterview(v:Video){const turningOn=!v.is_interview;setBusy(v.id);setMsg(turningOn&&yt.connected?'Marking interview and pulling transcript…':'Saving…');try{const r=await fetch('/api/admin/video-archive',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({action:'update',videoId:v.id,isInterview:turningOn})});const j=await r.json();if(!r.ok)throw new Error(j.error||'Could not update video');if(turningOn&&j.autoTranscript?.found)setMsg('Interview marked ✓ Transcript ready — it has moved to Transcribed.');else if(turningOn&&j.autoTranscript)setMsg(j.autoTranscript.error||j.autoTranscript.reason||'Interview marked. Transcript unavailable.');else setMsg(turningOn?'Interview marked.':'Interview flag removed.');await load()}catch(e){setMsg(e instanceof Error?e.message:'Could not update video')}finally{setBusy('')}}
 async function pullAllInterviewTranscripts(){setBusy('bulk-transcripts');setMsg('Pulling transcripts for marked interviews…');let processed=0,ready=0,failed=0;try{while(true){const r=await fetch('/api/admin/video-archive',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({action:'pull-interview-transcripts',limit:8})});const j=await r.json();if(!r.ok)throw new Error(j.error||'Transcript backfill failed');processed+=Number(j.processed||0);ready+=Number(j.ready||0);failed+=Number(j.failed||0);setMsg(`Transcripts: ${processed} checked · ${ready} ready · ${failed} unavailable${j.remaining?` · ${j.remaining} remaining…`:' — complete.'}`);if(!j.remaining||!j.processed)break}await load()}catch(e){setMsg(e instanceof Error?e.message:'Transcript backfill failed')}finally{setBusy('')}}
 const workVideos=useMemo(()=>videos.filter(v=>!v.is_interview||v.transcript_status!=='ready'),[videos]);
 const transcribedVideos=useMemo(()=>videos.filter(v=>v.is_interview&&v.transcript_status==='ready'&&v.moment_count===0),[videos]);
 const visibleVideos=tab==='videos'?workVideos:tab==='transcribed'?transcribedVideos:[];
 function toggle(id:string){setSelected(prev=>{const next=new Set(prev);next.has(id)?next.delete(id):next.add(id);return next})}
 const allSelected=visibleVideos.length>0&&visibleVideos.every(v=>selected.has(v.id));
 function toggleAll(){setSelected(allSelected?new Set():new Set(visibleVideos.map(v=>v.id)))}
 async function deleteSelected(){if(!selected.size)return;if(!window.confirm(`Permanently delete ${selected.size} selected videos from Guestlist?`))return;const result=await act({action:'delete-videos',videoIds:[...selected]},'delete-videos');if(result.ok)setSelected(new Set())}
 async function sendAllToCheck(){if(!moments.length)return;if(!window.confirm(`Move all ${moments.length} AI moments to the Check stage?`))return;await act({action:'bulk-stage'},'bulk-stage');setTab('check')}
 async function bulkCheck(decision:'publish'|'reject'){if(!checkMoments.length)return;const verb=decision==='publish'?'publish':'reject';if(!window.confirm(`${verb[0].toUpperCase()+verb.slice(1)} all ${checkMoments.length} checked moments?`))return;await act({action:'bulk-review',decision},`bulk-${decision}`);if(decision==='publish')setTab('final')}
 async function hideMoment(m:Moment){if(!window.confirm(`Hide “${m.title}”?`))return;await act({action:'hide-moment',momentId:m.id},m.id)}
 async function changeArtist(current:string,ms:Moment[]){const name=window.prompt(`Change artist for these interview clips.\n\nCurrent: ${current}\n\nEnter the exact artist name:`,'');if(!name?.trim())return;const videoIds=[...new Set(ms.map(m=>m.video_id))];await act({action:'change-artist',videoIds,artistName:name.trim()},`artist-${videoIds.join('-')}`)}
 const interviewsNeedingTranscript=videos.filter(v=>v.is_interview&&['missing','partial'].includes(v.transcript_status)).length;
 const tabs:[Tab,string,number][]=[['videos','1 · Videos',workVideos.length],['transcribed','2 · Transcribed',transcribedVideos.length],['ai','3 · AI moments',moments.length],['check','4 · Check',checkMoments.length],['final','5 · Final clips',publishedMoments.length]];

 const momentCard=(m:Moment,stage:'ai'|'check'|'final')=><div className="adminCard" key={m.id} style={{padding:18}}><div style={{display:'flex',justifyContent:'space-between',gap:16,alignItems:'start',flexWrap:'wrap'}}><div style={{maxWidth:900}}><div style={{fontSize:18,fontWeight:750}}>{m.title}</div><div className="adminSub" style={{marginTop:3}}>{m.video_title} · {clock(m.start_seconds)}{m.topic_label?` · ${m.topic_label}`:''}</div>{m.summary&&<p style={{margin:'12px 0 0',lineHeight:1.5}}>{m.summary}</p>}</div><div style={{display:'flex',gap:7,flexWrap:'wrap'}}><a className="btn btnSmall" target="_blank" rel="noreferrer" href={`https://www.youtube.com/watch?v=${m.youtube_video_id}&t=${m.start_seconds}s`}>{stage==='check'?'Check on YouTube ↗':'Open moment ↗'}</a>{stage==='ai'&&<><button className="btn btnSmall" disabled={!!busy} onClick={()=>act({action:'stage-moment',momentId:m.id},m.id)}>Send to check →</button><button className="btn btnSmall" disabled={!!busy} onClick={()=>hideMoment(m)}>Reject</button></>}{stage==='check'&&<><button className="btn btnSmall" disabled={!!busy} onClick={()=>act({action:'review',momentId:m.id,decision:'publish'},m.id)}>Publish ✓</button><button className="btn btnSmall" disabled={!!busy} onClick={()=>act({action:'review',momentId:m.id,decision:'reject'},m.id)}>Reject</button></>}{stage==='final'&&<button className="btn btnSmall" disabled={!!busy} onClick={()=>hideMoment(m)}>Hide</button>}</div></div></div>;
 const artistGroups=(items:Moment[],stage:'ai'|'check'|'final')=>groupByArtist(items).map(([artist,ms])=><section key={artist} style={{marginTop:26}}><div style={{display:'flex',alignItems:'baseline',justifyContent:'space-between',gap:12,borderBottom:'1px solid var(--border)',paddingBottom:8,marginBottom:10,flexWrap:'wrap'}}><div><div style={{fontSize:22,fontWeight:800}}>{artist}</div><div className="adminSub">{ms.length} {stage==='final'?'published clip':'moment'}{ms.length===1?'':'s'}</div></div><div style={{display:'flex',gap:8,flexWrap:'wrap'}}><button className="btn btnSmall" disabled={!!busy} onClick={()=>changeArtist(artist,ms)}>Change artist</button>{ms[0]?.artist_slug&&<a className="btn btnSmall" href={`/artists/${ms[0].artist_slug}`} target="_blank">Artist page ↗</a>}</div></div><div style={{display:'grid',gap:10}}>{ms.map(m=>momentCard(m,stage))}</div></section>);

 return <div><div className="adminHeader"><div><h1>Video Archive</h1><p className="adminSub">A simple production line: find interview → transcript → AI moments → check → publish.</p></div><div style={{display:'flex',gap:8,flexWrap:'wrap'}}><a className="btn" href="/api/admin/video-archive/youtube/connect">{yt.connected?`YouTube ✓${yt.channel_title?` · ${yt.channel_title}`:''}`:'Connect YouTube'}</a><button className="btn" disabled={!!busy} onClick={sync}>{busy==='sync'?'Syncing…':'Sync YouTube'}</button>{yt.connected&&<button className="btn" disabled={!!busy||!interviewsNeedingTranscript} onClick={pullAllInterviewTranscripts}>{busy==='bulk-transcripts'?'Pulling…':`Pull transcripts${interviewsNeedingTranscript?` (${interviewsNeedingTranscript})`:''}`}</button>}</div></div>
 {msg&&<div className="adminCard" style={{marginTop:14,padding:'12px 16px'}}>{msg}</div>}
 <div style={{display:'flex',gap:8,marginTop:24,flexWrap:'wrap',paddingBottom:12,borderBottom:'1px solid var(--border)'}}>{tabs.map(([key,label,count])=><button key={key} className="btn" onClick={()=>{setTab(key);setSelected(new Set())}} aria-pressed={tab===key} style={tab===key?{fontWeight:800}:undefined}>{label} <span style={{opacity:.65}}>({count})</span></button>)}</div>

 {(tab==='videos'||tab==='transcribed')&&<>{visibleVideos.length>0&&<div className="adminCard" style={{display:'flex',alignItems:'center',justifyContent:'space-between',gap:12,marginTop:14,flexWrap:'wrap'}}><label style={{display:'flex',alignItems:'center',gap:8,cursor:'pointer'}}><input type="checkbox" checked={allSelected} onChange={toggleAll}/><b>Select all visible</b><span className="adminSub">{selected.size?`${selected.size} selected`:`${visibleVideos.length} videos`}</span></label><button className="btn btnSmall" disabled={!selected.size||!!busy} onClick={deleteSelected}>Delete selected</button></div>}
 <div style={{display:'grid',gap:12,marginTop:12}}>{visibleVideos.map(v=><div className="adminCard" key={v.id}><div style={{display:'grid',gridTemplateColumns:'28px 120px minmax(260px,1fr) auto',gap:14,alignItems:'center'}}><input type="checkbox" checked={selected.has(v.id)} onChange={()=>toggle(v.id)}/>{v.thumbnail_url?<img src={v.thumbnail_url} alt="" style={{width:120,aspectRatio:'16/9',objectFit:'cover',borderRadius:8}}/>:<div/>}<div><div style={{fontWeight:750}}>{v.title}</div><div className="adminSub">{v.artists?.map(a=>a.name).join(', ')||'Artist not matched'} · transcript {v.transcript_status}</div></div><div style={{display:'flex',gap:7,flexWrap:'wrap'}}>{tab==='videos'&&<button className="btn btnSmall" disabled={busy===v.id} onClick={()=>toggleInterview(v)}>{v.is_interview?'Interview ✓':'Mark interview'}</button>}{tab==='videos'&&v.is_interview&&v.transcript_status!=='ready'&&yt.connected&&<button className="btn btnSmall" disabled={!!busy} onClick={()=>act({action:'pull-transcript',videoId:v.id},`transcript-${v.id}`)}>Retry transcript</button>}{tab==='transcribed'&&<button className="btn btnSmall" disabled={!!busy} onClick={async()=>{const r=await act({action:'extract',videoId:v.id},`moments-${v.id}`);if(r.ok)setTab('ai')}}>{busy===`moments-${v.id}`?'Creating moments…':'Generate AI moments →'}</button>}</div></div>{tab==='videos'&&v.is_interview&&v.transcript_status!=='ready'&&<div style={{marginTop:12}}><textarea value={transcript[v.id]||''} onChange={e=>setTranscript({...transcript,[v.id]:e.target.value})} placeholder="Paste transcript manually if YouTube captions are unavailable" rows={4} style={{width:'100%'}}/><button className="btn btnSmall" disabled={!transcript[v.id]?.trim()} onClick={()=>act({action:'update',videoId:v.id,transcript:transcript[v.id]})}>Save transcript</button></div>}</div>)}</div>{!visibleVideos.length&&<p className="adminSub" style={{marginTop:24}}>Nothing waiting at this stage.</p>}</>}

 {tab==='ai'&&<>{moments.length>0?<><div style={{display:'flex',justifyContent:'space-between',alignItems:'center',gap:12,marginTop:24,flexWrap:'wrap'}}><div><h2 style={{margin:0}}>AI moments</h2><p className="adminSub">First pass. Keep the interesting ones and send them forward to Check.</p></div><button className="btn" disabled={!!busy} onClick={sendAllToCheck}>{busy==='bulk-stage'?'Moving…':'Send all to Check →'}</button></div>{artistGroups(moments,'ai')}</>:<p className="adminSub" style={{marginTop:24}}>No AI moments waiting. Generate them from the Transcribed tab.</p>}</>}

 {tab==='check'&&<>{checkMoments.length>0?<><div style={{display:'flex',justifyContent:'space-between',alignItems:'center',gap:12,marginTop:24,flexWrap:'wrap'}}><div><h2 style={{margin:0}}>Check before publishing</h2><p className="adminSub">Open the timestamp, confirm it is a genuinely good moment, then publish.</p></div><div style={{display:'flex',gap:8}}><button className="btn" disabled={!!busy} onClick={()=>bulkCheck('publish')}>Publish all checked</button><button className="btn" disabled={!!busy} onClick={()=>bulkCheck('reject')}>Reject all</button></div></div>{artistGroups(checkMoments,'check')}</>:<p className="adminSub" style={{marginTop:24}}>Nothing waiting to be checked.</p>}</>}

 {tab==='final'&&<>{publishedMoments.length>0?<><div style={{marginTop:24}}><h2 style={{margin:0}}>Final clips</h2><p className="adminSub">Published Guestlist interview moments, organised by artist.</p></div>{artistGroups(publishedMoments,'final')}</>:<p className="adminSub" style={{marginTop:24}}>No final clips published yet.</p>}</>}
 </div>
}
