'use client';
import { useState } from 'react';

type A={id:string;title:string;subtitle:string|null;author_name:string;status:string;article_type:string;hero_image_url:string|null;hero_image_alt:string|null;excerpt:string|null;body:string;tags:string[];admin_note:string|null;featured:boolean;updated_at:string;view_count:number;slug:string};
const TYPES=['story','opinion','guide','interview','reflection','photo-essay','list'];
export function AdminArticles({initial}:{initial:A[]}){
 const [items,setItems]=useState(initial);const [notes,setNotes]=useState<Record<string,string>>({});const [busy,setBusy]=useState<string|null>(null);const [msg,setMsg]=useState('');const [editing,setEditing]=useState<string|null>(null);
 function patch(id:string,p:Partial<A>){setItems(xs=>xs.map(x=>x.id===id?{...x,...p}:x))}
 async function request(id:string,payload:Record<string,unknown>){setBusy(id);setMsg('');try{const r=await fetch(`/api/admin/articles/${id}`,{method:'PATCH',headers:{'content-type':'application/json'},body:JSON.stringify(payload)});const d=await r.json();if(!r.ok)throw new Error(d.error||'Failed');setItems(xs=>xs.map(x=>x.id===id?d.article:x));setMsg('Updated.');return true;}catch(e){setMsg(e instanceof Error?e.message:'Failed');return false}finally{setBusy(null)}}
 async function act(id:string,action:string,featured?:boolean){await request(id,{action,note:notes[id]||'',featured})}
 async function saveEdit(a:A){const ok=await request(a.id,{action:'edit',title:a.title,subtitle:a.subtitle,excerpt:a.excerpt,body:a.body,article_type:a.article_type,hero_image_url:a.hero_image_url,hero_image_alt:a.hero_image_alt,tags:a.tags});if(ok)setEditing(null)}
 return <div style={{padding:'28px 0 60px'}}><div style={{display:'flex',justifyContent:'space-between',gap:16,alignItems:'end',marginBottom:22}}><div><div className="sectionLabel">Editorial</div><h1 style={{margin:'5px 0 0'}}>Balance articles</h1></div><span style={{color:'var(--text-muted)'}}>{items.filter(x=>x.status==='submitted').length} waiting</span></div>{msg&&<p style={{color:'var(--text-muted)'}}>{msg}</p>}<div style={{display:'grid',gap:16}}>{items.map(a=><article key={a.id} style={{border:'1px solid var(--border)',borderRadius:'var(--radius)',padding:18,display:'grid',gridTemplateColumns:a.hero_image_url?'180px 1fr':'1fr',gap:18,background:'var(--bg-raised)'}}>{a.hero_image_url&&<img src={a.hero_image_url} alt="" style={{width:'100%',aspectRatio:'4/3',objectFit:'cover',borderRadius:12}}/>}<div><div style={{display:'flex',gap:8,flexWrap:'wrap',fontSize:11,textTransform:'uppercase',letterSpacing:'.08em',color:'var(--accent-ink)',fontWeight:800}}><span>{a.status.replace('_',' ')}</span><span>· {a.article_type}</span><span>· {a.author_name}</span><span>· {a.view_count} views</span>{a.featured&&<span>· Featured</span>}</div><h2 style={{margin:'7px 0'}}>{a.title||'Untitled draft'}</h2>{a.excerpt&&<p style={{color:'var(--text-soft)',margin:'0 0 10px'}}>{a.excerpt}</p>}
 {editing===a.id?<div style={{display:'grid',gap:9,marginTop:12}}><input value={a.title} onChange={e=>patch(a.id,{title:e.target.value})} placeholder="Headline" style={field}/><input value={a.subtitle||''} onChange={e=>patch(a.id,{subtitle:e.target.value})} placeholder="Subtitle" style={field}/><select value={a.article_type} onChange={e=>patch(a.id,{article_type:e.target.value})} style={field}>{TYPES.map(t=><option key={t}>{t}</option>)}</select><textarea value={a.excerpt||''} onChange={e=>patch(a.id,{excerpt:e.target.value})} rows={2} placeholder="Excerpt" style={field}/><textarea value={a.body} onChange={e=>patch(a.id,{body:e.target.value})} rows={14} style={{...field,lineHeight:1.55}}/><input value={a.hero_image_url||''} onChange={e=>patch(a.id,{hero_image_url:e.target.value})} placeholder="Hero image URL" style={field}/><input value={a.tags.join(', ')} onChange={e=>patch(a.id,{tags:e.target.value.split(',').map(x=>x.trim()).filter(Boolean)})} placeholder="Tags" style={field}/><div style={{display:'flex',gap:8}}><button className="btnAccent" disabled={busy===a.id} onClick={()=>saveEdit(a)}>Save editorial edits</button><button className="btnGhost" onClick={()=>setEditing(null)}>Close</button></div></div>:<details><summary style={{cursor:'pointer',color:'var(--text-muted)'}}>Read draft</summary><div style={{whiteSpace:'pre-wrap',lineHeight:1.6,maxWidth:760,marginTop:10}}>{a.body}</div></details>}
 <textarea value={notes[a.id]??a.admin_note??''} onChange={e=>setNotes(n=>({...n,[a.id]:e.target.value}))} placeholder="Editor note / requested changes" rows={3} style={{...field,marginTop:12}}/><div style={{display:'flex',gap:8,flexWrap:'wrap',marginTop:10}}><button className="btnGhost" disabled={busy===a.id} onClick={()=>setEditing(editing===a.id?null:a.id)}>{editing===a.id?'Close edit':'Edit article'}</button><button className="btnGhost" disabled={busy===a.id} onClick={()=>act(a.id,'request_changes')}>Request changes</button><button className="btnGhost" disabled={busy===a.id} onClick={()=>act(a.id,'approve')}>Approve</button><button className="btnAccent" disabled={busy===a.id} onClick={()=>act(a.id,'publish')}>Publish</button><button className="btnGhost" disabled={busy===a.id} onClick={()=>act(a.id,'feature',!a.featured)}>{a.featured?'Unfeature':'Feature'}</button>{a.status==='published'&&<a className="btnGhost" href={`/balance/${a.slug}`} target="_blank">View live ↗</a>}<button className="btnGhost" disabled={busy===a.id} onClick={()=>act(a.id,'reject')}>Reject</button>{a.status==='published'&&<button className="btnGhost" disabled={busy===a.id} onClick={()=>act(a.id,'archive')}>Archive</button>}</div></div></article>)}</div></div>}
const field:React.CSSProperties={width:'100%',padding:10,border:'1px solid var(--border)',borderRadius:10,background:'var(--bg)',color:'var(--text)',font:'inherit'};
