import type { Metadata } from 'next';
import Link from 'next/link';
import { notFound } from 'next/navigation';
import { getCurrentMember } from '@/lib/auth';
import { getPublishedArticle, recordArticleView } from '@/lib/articles';
import styles from '../balance.module.css';
export const dynamic='force-dynamic';
export async function generateMetadata({params}:{params:Promise<{slug:string}>}):Promise<Metadata>{const {slug}=await params;const a=await getPublishedArticle(slug);if(!a)return {title:'Balance · Guestlist'};return {title:`${a.title} · Balance · Guestlist`,description:a.excerpt||a.subtitle||undefined,openGraph:{title:a.title,description:a.excerpt||a.subtitle||undefined,images:a.hero_image_url?[a.hero_image_url]:undefined,type:'article',publishedTime:a.published_at||undefined,authors:[a.author_name]}};}
export default async function ArticlePage({params}:{params:Promise<{slug:string}>}){const {slug}=await params;const [a,member]=await Promise.all([getPublishedArticle(slug),getCurrentMember()]);if(!a)notFound();await recordArticleView(a.id,member?.id||null).catch(()=>undefined);const paragraphs=a.body.split(/\n\s*\n/).map(x=>x.trim()).filter(Boolean);const author=a.author_slug?<Link href={`/members/${a.author_slug}`}>{a.author_name}</Link>:a.author_name;const isUnsplash=a.image_provider==='unsplash';const isPixabay=a.image_provider==='pixabay';return <main><article className={styles.article}><div className={styles.articleHead}><Link href="/balance" className={styles.kicker}>Balance</Link><h1 className={styles.articleTitle}>{a.title}</h1>{a.subtitle&&<p className={styles.subtitle}>{a.subtitle}</p>}<div className={styles.byline}>{a.author_avatar_url?<img className={styles.avatar} src={a.author_avatar_url} alt=""/>:<span className={styles.avatar}/>}<span>By {author} · {a.reading_minutes} min read{a.published_at?` · ${new Date(a.published_at).toLocaleDateString('en-GB',{day:'numeric',month:'long',year:'numeric'})}`:''}</span></div></div>{a.hero_image_url&&<><div className={styles.articleHero}><img src={a.hero_image_url} alt={a.hero_image_alt||''}/></div>{a.image_credit&&<div className={styles.credit}>Photo by {a.image_source_url?<a href={a.image_source_url} target="_blank" rel="noreferrer">{a.image_credit}</a>:a.image_credit}{isUnsplash&&<> on <a href="https://unsplash.com/?utm_source=guestlist&utm_medium=referral" target="_blank" rel="noreferrer">Unsplash</a></>}{isPixabay&&<> via <a href="https://pixabay.com/" target="_blank" rel="noreferrer">Pixabay</a></>}</div>}</>}<div className={styles.body}>{paragraphs.map((p,i)=><p key={i}>{p}</p>)}</div>{a.tags.length>0&&<div className={styles.tags}>{a.tags.map(t=><span className={styles.tag} key={t}>{t}</span>)}</div>}</article></main>}
